### ISSUE TITLE
Mostly Fails on cpantesters

### ISSUE THREAD

**Issue by andk** [nichtich/App-makedpkg#2]
Best illustrated by the matrix:

http://matrix.cpantesters.org/?dist=App-makedpkg%200.04

Looking at the first Fail report, http://www.cpantesters.org/cpan/report/40580116 , I spotted:

'pwd' is not recognized as an internal or external command,
operable program or batch file.

Maybe you want to replace the use of pwd with 'use Cwd; Cwd::getcwd()' or something like that?

HTH && Thanks,

(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by nichtich** [comment]
Thanks for the note. Using the application on Windows makes no sense, so I added a check to skip tests in this case. I hope to have fixed most of the remaining failures too.
